#!/usr/bin/env python3
"""
minify_static_css.py — Minify inline <style> blocks in all static HTML pages.

Processes every HTML file outside blog/posts/, blog/tags/, blog/archive/,
and blog/topic/ (those are generated by build_blog.py with already-minified CSS).
Uses the same minification approach as build_blog.py's _minify_css function.

Usage:
    python3 minify_static_css.py
"""

import os
import re
import sys
from pathlib import Path

SITE_ROOT = Path(__file__).resolve().parent

# Directories whose HTML is generated by build_blog.py (already minified)
SKIP_PREFIXES = (
    os.path.join(SITE_ROOT, "blog", "posts"),
    os.path.join(SITE_ROOT, "blog", "tags"),
    os.path.join(SITE_ROOT, "blog", "archive"),
    os.path.join(SITE_ROOT, "blog", "topic"),
    os.path.join(SITE_ROOT, "blog", "2"),      # blog/2024/..., blog/2025/..., blog/2026/...
)

# Also skip the blog index itself (generated by build_blog.py)
SKIP_FILES = {
    os.path.join(SITE_ROOT, "blog", "index.html"),
}


def minify_css(css):
    """Collapse whitespace in CSS for smaller inline output.

    Same algorithm as build_blog.py _minify_css().
    """
    css = re.sub(r'/\*.*?\*/', '', css, flags=re.DOTALL)   # strip comments
    css = re.sub(r'\s+', ' ', css)                          # collapse whitespace
    css = re.sub(r'\s*([{}:;,>~+])\s*', r'\1', css)        # remove space around punctuation
    css = re.sub(r';}', '}', css)                           # remove trailing semicolons
    return css.strip()


STYLE_RE = re.compile(r'(<style[^>]*>)(.*?)(</style>)', flags=re.DOTALL)


def process_file(filepath):
    """Minify all <style> blocks in a single HTML file. Returns bytes saved."""
    with open(filepath, 'r', encoding='utf-8') as f:
        original = f.read()

    def _replace(m):
        open_tag = m.group(1)
        css_body = m.group(2)
        close_tag = m.group(3)
        return open_tag + minify_css(css_body) + close_tag

    updated = STYLE_RE.sub(_replace, original)

    if updated == original:
        return 0

    saved = len(original.encode('utf-8')) - len(updated.encode('utf-8'))
    with open(filepath, 'w', encoding='utf-8') as f:
        f.write(updated)
    return saved


def should_skip(filepath):
    """Return True if this file is generated content (already minified)."""
    fp = str(filepath)
    if fp in SKIP_FILES:
        return True
    for prefix in SKIP_PREFIXES:
        if fp.startswith(prefix):
            return True
    return False


def main():
    total_saved = 0
    files_changed = 0
    files_checked = 0

    for root, _dirs, files in os.walk(SITE_ROOT):
        # Skip hidden dirs (.git, .github, etc.)
        if os.path.basename(root).startswith('.'):
            continue
        for fname in files:
            if not fname.endswith('.html'):
                continue
            filepath = os.path.join(root, fname)
            if should_skip(filepath):
                continue
            files_checked += 1
            saved = process_file(filepath)
            if saved > 0:
                files_changed += 1
                total_saved += saved
                print(f"  {os.path.relpath(filepath, SITE_ROOT):50s}  -{saved:,} bytes")

    print(f"\nMinified CSS in {files_changed}/{files_checked} static HTML files")
    print(f"Total saved: {total_saved:,} bytes ({total_saved/1024:.1f} KB)")


if __name__ == '__main__':
    main()
